
# Autogenerated by mlir-tblgen; don't manually edit.
from __future__ import annotations


from mlir.dialects._ods_common import _cext as _ods_cext
from mlir.dialects._ods_common import (
    equally_sized_accessor as _ods_equally_sized_accessor,
    get_default_loc_context as _ods_get_default_loc_context,
    get_op_result_or_op_results as _get_op_result_or_op_results,
    get_op_result_or_value as _get_op_result_or_value,
    get_op_results_or_values as _get_op_results_or_values,
    segmented_accessor as _ods_segmented_accessor,
)
_ods_ir = _ods_cext.ir

import builtins
from typing import Sequence as _Sequence, Union as _Union


@_ods_cext.register_dialect
class _Dialect(_ods_ir.Dialect):
  DIALECT_NAMESPACE = "tla"

@_ods_cext.register_operation(_Dialect)
class AbsOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.abs"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, operand, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(operand))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def operand(self):
    return self.operation.operands[0]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 2 else self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def abs(result, operand, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(AbsOp(result=result, operand=operand, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class AddOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.add"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def add(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(AddOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class AddsOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.adds"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def adds(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(AddsOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class AllocPtrOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.alloc_ptr"

  _ODS_REGIONS = (0, True)

  def __init__(self, ptr, size_bytes, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["size_bytes"] = (size_bytes if (
    isinstance(size_bytes, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64Attr')) else
      _ods_ir.AttrBuilder.get('I64Attr')(size_bytes, context=_ods_context))
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def size_bytes(self):
    return self.operation.attributes["size_bytes"]

  @size_bytes.setter
  def size_bytes(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["size_bytes"] = value

  @builtins.property
  def ptr(self):
    return self.operation.results[0]

def alloc_ptr(ptr, size_bytes, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(AllocPtrOp(ptr=ptr, size_bytes=size_bytes, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class ArangeOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.arange"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, start, order, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(start))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["order"] = (order if (
    isinstance(order, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(order, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def start(self):
    return self.operation.operands[0]

  @builtins.property
  def order(self):
    return self.operation.attributes["order"]

  @order.setter
  def order(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["order"] = value

  @builtins.property
  def result(self):
    return self.operation.results[0]

def arange(result, start, order, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(ArangeOp(result=result, start=start, order=order, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class BitwiseAndOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.bitwise_and"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def bitwise_and(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(BitwiseAndOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class BitwiseNotOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.bitwise_not"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, operand, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(operand))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def operand(self):
    return self.operation.operands[0]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 2 else self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def bitwise_not(result, operand, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(BitwiseNotOp(result=result, operand=operand, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class BitwiseOrOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.bitwise_or"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def bitwise_or(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(BitwiseOrOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class BitwiseXorOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.bitwise_xor"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def bitwise_xor(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(BitwiseXorOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class BlockDimOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.arch.block_dim"

  _ODS_REGIONS = (0, True)

  def __init__(self, dim, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(dim)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dim(self):
    return self.operation.results[0]

def arch_block_dim(dim, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(BlockDimOp(dim=dim, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class BlockIdxOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.arch.block_idx"

  _ODS_REGIONS = (0, True)

  def __init__(self, index, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(index)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def index(self):
    return self.operation.results[0]

def arch_block_idx(index, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(BlockIdxOp(index=index, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CastOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.cast"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, source, trait, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(source))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["trait"] = (trait if (
    isinstance(trait, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('DenseI32ArrayAttr')) else
      _ods_ir.AttrBuilder.get('DenseI32ArrayAttr')(trait, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def source(self):
    return self.operation.operands[0]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 2 else self.operation.operands[1]

  @builtins.property
  def trait(self):
    return self.operation.attributes["trait"]

  @trait.setter
  def trait(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["trait"] = value

  @builtins.property
  def result(self):
    return self.operation.results[0]

def cast(result, source, trait, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(CastOp(result=result, source=source, trait=trait, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CmpOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.cmp"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, mode, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["mode"] = (mode if (
    isinstance(mode, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(mode, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def mode(self):
    return self.operation.attributes["mode"]

  @mode.setter
  def mode(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["mode"] = value

  @builtins.property
  def result(self):
    return self.operation.results[0]

def cmp(result, lhs, rhs, mode, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(CmpOp(result=result, lhs=lhs, rhs=rhs, mode=mode, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CopyL0C2DstParamsOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.CopyL0C2DstParams"

  _ODS_REGIONS = (0, True)

  def __init__(self, params, unit_flag, relu_enable, quant_mode, l0c2ub_mode, *, quant_scale_or_tensor=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    if quant_scale_or_tensor is not None: operands.append(_get_op_result_or_value(quant_scale_or_tensor))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["unit_flag"] = (unit_flag if (
    isinstance(unit_flag, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64Attr')) else
      _ods_ir.AttrBuilder.get('I64Attr')(unit_flag, context=_ods_context))
    attributes["relu_enable"] = (relu_enable if (
    isinstance(relu_enable, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('BoolAttr')) else
      _ods_ir.AttrBuilder.get('BoolAttr')(relu_enable, context=_ods_context))
    attributes["quant_mode"] = (quant_mode if (
    isinstance(quant_mode, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_QuantModeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_QuantModeAttr')(quant_mode, context=_ods_context))
    attributes["l0c2ub_mode"] = (l0c2ub_mode if (
    isinstance(l0c2ub_mode, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_L0C2UBModeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_L0C2UBModeAttr')(l0c2ub_mode, context=_ods_context))
    results.append(params)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def quant_scale_or_tensor(self):
    return None if len(self.operation.operands) < 1 else self.operation.operands[0]

  @builtins.property
  def unit_flag(self):
    return self.operation.attributes["unit_flag"]

  @unit_flag.setter
  def unit_flag(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["unit_flag"] = value

  @builtins.property
  def relu_enable(self):
    return self.operation.attributes["relu_enable"]

  @relu_enable.setter
  def relu_enable(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["relu_enable"] = value

  @builtins.property
  def quant_mode(self):
    return self.operation.attributes["quant_mode"]

  @quant_mode.setter
  def quant_mode(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["quant_mode"] = value

  @builtins.property
  def l0c2ub_mode(self):
    return self.operation.attributes["l0c2ub_mode"]

  @l0c2ub_mode.setter
  def l0c2ub_mode(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["l0c2ub_mode"] = value

  @builtins.property
  def params(self):
    return self.operation.results[0]

def CopyL0C2DstParams(params, unit_flag, relu_enable, quant_mode, l0c2ub_mode, *, quant_scale_or_tensor=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(CopyL0C2DstParamsOp(params=params, unit_flag=unit_flag, relu_enable=relu_enable, quant_mode=quant_mode, l0c2ub_mode=l0c2ub_mode, quant_scale_or_tensor=quant_scale_or_tensor, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CopyOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.copy"

  _ODS_REGIONS = (0, True)

  def __init__(self, dst, src, *, params=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(dst))
    operands.append(_get_op_result_or_value(src))
    if params is not None: operands.append(_get_op_result_or_value(params))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dst(self):
    return self.operation.operands[0]

  @builtins.property
  def src(self):
    return self.operation.operands[1]

  @builtins.property
  def params(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

def copy(dst, src, *, params=None, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(CopyOp(dst=dst, src=src, params=params, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CreateMaskOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.create_mask"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, pattern, dtype, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["pattern"] = (pattern if (
    isinstance(pattern, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(pattern, context=_ods_context))
    attributes["dtype"] = (dtype if (
    isinstance(dtype, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('TypeAttr')) else
      _ods_ir.AttrBuilder.get('TypeAttr')(dtype, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def pattern(self):
    return self.operation.attributes["pattern"]

  @pattern.setter
  def pattern(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["pattern"] = value

  @builtins.property
  def dtype(self):
    return self.operation.attributes["dtype"]

  @dtype.setter
  def dtype(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dtype"] = value

  @builtins.property
  def result(self):
    return self.operation.results[0]

def create_mask(result, pattern, dtype, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(CreateMaskOp(result=result, pattern=pattern, dtype=dtype, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CrossCoreSetFlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.cross_core_set_flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, pipe, *, aiv_id=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(flag))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["pipe"] = (pipe if (
    isinstance(pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(pipe, context=_ods_context))
    if aiv_id is not None: attributes["aiv_id"] = (aiv_id if (
        isinstance(aiv_id, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('I64Attr')) else
          _ods_ir.AttrBuilder.get('I64Attr')(aiv_id, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def flag(self):
    return self.operation.operands[0]

  @builtins.property
  def pipe(self):
    return self.operation.attributes["pipe"]

  @pipe.setter
  def pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["pipe"] = value

  @builtins.property
  def aiv_id(self):
    if "aiv_id" not in self.operation.attributes:
      return None
    return self.operation.attributes["aiv_id"]

  @aiv_id.setter
  def aiv_id(self, value):
    if value is not None:
      self.operation.attributes["aiv_id"] = value
    elif "aiv_id" in self.operation.attributes:
      del self.operation.attributes["aiv_id"]

  @aiv_id.deleter
  def aiv_id(self):
    del self.operation.attributes["aiv_id"]

def cross_core_set_flag(flag, pipe, *, aiv_id=None, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(CrossCoreSetFlagOp(flag=flag, pipe=pipe, aiv_id=aiv_id, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CrossCoreWaitFlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.cross_core_wait_flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, pipe, *, aiv_id=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(flag))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["pipe"] = (pipe if (
    isinstance(pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(pipe, context=_ods_context))
    if aiv_id is not None: attributes["aiv_id"] = (aiv_id if (
        isinstance(aiv_id, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('I64Attr')) else
          _ods_ir.AttrBuilder.get('I64Attr')(aiv_id, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def flag(self):
    return self.operation.operands[0]

  @builtins.property
  def pipe(self):
    return self.operation.attributes["pipe"]

  @pipe.setter
  def pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["pipe"] = value

  @builtins.property
  def aiv_id(self):
    if "aiv_id" not in self.operation.attributes:
      return None
    return self.operation.attributes["aiv_id"]

  @aiv_id.setter
  def aiv_id(self, value):
    if value is not None:
      self.operation.attributes["aiv_id"] = value
    elif "aiv_id" in self.operation.attributes:
      del self.operation.attributes["aiv_id"]

  @aiv_id.deleter
  def aiv_id(self):
    del self.operation.attributes["aiv_id"]

def cross_core_wait_flag(flag, pipe, *, aiv_id=None, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(CrossCoreWaitFlagOp(flag=flag, pipe=pipe, aiv_id=aiv_id, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CrossFlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.cross_flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, name, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["name"] = (name if (
    isinstance(name, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(name, context=_ods_context))
    results.append(flag)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def name(self):
    return self.operation.attributes["name"]

  @name.setter
  def name(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["name"] = value

  @builtins.property
  def flag(self):
    return self.operation.results[0]

def cross_flag(flag, name, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(CrossFlagOp(flag=flag, name=name, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CubeOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.cube"

  _ODS_REGIONS = (1, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def body(self):
    return self.regions[0]

def cube(*, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(CubeOp(loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class DeInterleaveOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.deinterleave"

  _ODS_REGIONS = (0, True)

  def __init__(self, dst0, dst1, src0, src1, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(src0))
    operands.append(_get_op_result_or_value(src1))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(dst0)
    results.append(dst1)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def src0(self):
    return self.operation.operands[0]

  @builtins.property
  def src1(self):
    return self.operation.operands[1]

  @builtins.property
  def dst0(self):
    return self.operation.results[0]

  @builtins.property
  def dst1(self):
    return self.operation.results[1]

def deinterleave(dst0, dst1, src0, src1, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return _get_op_result_or_op_results(DeInterleaveOp(dst0=dst0, dst1=dst1, src0=src0, src1=src1, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class DebugPrintOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.debug_print"

  _ODS_REGIONS = (0, True)

  def __init__(self, value, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(value))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def value(self):
    return self.operation.operands[0]

def debug_print(value, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(DebugPrintOp(value=value, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class DivOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.div"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def div(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(DivOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class DivsOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.divs"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def divs(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(DivsOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class ExpOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.exp"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, operand, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(operand))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def operand(self):
    return self.operation.operands[0]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 2 else self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def exp(result, operand, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(ExpOp(result=result, operand=operand, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class FlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, name, src_pipe, dst_pipe, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["name"] = (name if (
    isinstance(name, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(name, context=_ods_context))
    attributes["src_pipe"] = (src_pipe if (
    isinstance(src_pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(src_pipe, context=_ods_context))
    attributes["dst_pipe"] = (dst_pipe if (
    isinstance(dst_pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(dst_pipe, context=_ods_context))
    results.append(flag)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def name(self):
    return self.operation.attributes["name"]

  @name.setter
  def name(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["name"] = value

  @builtins.property
  def src_pipe(self):
    return self.operation.attributes["src_pipe"]

  @src_pipe.setter
  def src_pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["src_pipe"] = value

  @builtins.property
  def dst_pipe(self):
    return self.operation.attributes["dst_pipe"]

  @dst_pipe.setter
  def dst_pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dst_pipe"] = value

  @builtins.property
  def flag(self):
    return self.operation.results[0]

def flag(flag, name, src_pipe, dst_pipe, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(FlagOp(flag=flag, name=name, src_pipe=src_pipe, dst_pipe=dst_pipe, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class FullOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.full"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, value, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(value))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def value(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def full(result, value, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(FullOp(result=result, value=value, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class FuncOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.func"

  _ODS_REGIONS = (1, True)

  def __init__(self, sym_name, function_type, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["sym_name"] = (sym_name if (
    isinstance(sym_name, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('SymbolNameAttr')) else
      _ods_ir.AttrBuilder.get('SymbolNameAttr')(sym_name, context=_ods_context))
    attributes["function_type"] = (function_type if (
    isinstance(function_type, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('TypeAttr')) else
      _ods_ir.AttrBuilder.get('TypeAttr')(function_type, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def sym_name(self):
    return self.operation.attributes["sym_name"]

  @sym_name.setter
  def sym_name(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["sym_name"] = value

  @builtins.property
  def function_type(self):
    return self.operation.attributes["function_type"]

  @function_type.setter
  def function_type(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["function_type"] = value

  @builtins.property
  def body(self):
    return self.regions[0]

def func(sym_name, function_type, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(FuncOp(sym_name=sym_name, function_type=function_type, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class GatherOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.gather"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, x, y, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(x))
    operands.append(_get_op_result_or_value(y))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def x(self):
    return self.operation.operands[0]

  @builtins.property
  def y(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def gather(result, x, y, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(GatherOp(result=result, x=x, y=y, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class IntToPtrOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.inttoptr"

  _ODS_REGIONS = (0, True)

  def __init__(self, ptr, addr, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(addr))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def addr(self):
    return self.operation.operands[0]

  @builtins.property
  def ptr(self):
    return self.operation.results[0]

def inttoptr(ptr, addr, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(IntToPtrOp(ptr=ptr, addr=addr, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class InterleaveOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.interleave"

  _ODS_REGIONS = (0, True)

  def __init__(self, dst0, dst1, src0, src1, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(src0))
    operands.append(_get_op_result_or_value(src1))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(dst0)
    results.append(dst1)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def src0(self):
    return self.operation.operands[0]

  @builtins.property
  def src1(self):
    return self.operation.operands[1]

  @builtins.property
  def dst0(self):
    return self.operation.results[0]

  @builtins.property
  def dst1(self):
    return self.operation.results[1]

def interleave(dst0, dst1, src0, src1, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return _get_op_result_or_op_results(InterleaveOp(dst0=dst0, dst1=dst1, src0=src0, src1=src1, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class LoadOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.load"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, result2, source, *, load_dist=None, unaligned_ub_access=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(source))
    _ods_context = _ods_get_default_loc_context(loc)
    if load_dist is not None: attributes["load_dist"] = (load_dist if (
        isinstance(load_dist, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('Tla_LoadDistAttr')) else
          _ods_ir.AttrBuilder.get('Tla_LoadDistAttr')(load_dist, context=_ods_context))
    if bool(unaligned_ub_access): attributes["unaligned_ub_access"] = _ods_ir.UnitAttr.get(
      _ods_get_default_loc_context(loc))
    results.append(result)
    if result2 is not None: results.append(result2)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def source(self):
    return self.operation.operands[0]

  @builtins.property
  def load_dist(self):
    if "load_dist" not in self.operation.attributes:
      return None
    return self.operation.attributes["load_dist"]

  @load_dist.setter
  def load_dist(self, value):
    if value is not None:
      self.operation.attributes["load_dist"] = value
    elif "load_dist" in self.operation.attributes:
      del self.operation.attributes["load_dist"]

  @load_dist.deleter
  def load_dist(self):
    del self.operation.attributes["load_dist"]

  @builtins.property
  def unaligned_ub_access(self):
    return "unaligned_ub_access" in self.operation.attributes

  @unaligned_ub_access.setter
  def unaligned_ub_access(self, value):
    if bool(value):
      self.operation.attributes["unaligned_ub_access"] = _ods_ir.UnitAttr.get()
    elif "unaligned_ub_access" in self.operation.attributes:
      del self.operation.attributes["unaligned_ub_access"]

  @unaligned_ub_access.deleter
  def unaligned_ub_access(self):
    del self.operation.attributes["unaligned_ub_access"]

  @builtins.property
  def result(self):
    return self.operation.results[0]

  @builtins.property
  def result2(self):
    return None if len(self.operation.results) < 2 else self.operation.results[1]

def load(result, result2, source, *, load_dist=None, unaligned_ub_access=None, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return _get_op_result_or_op_results(LoadOp(result=result, result2=result2, source=source, load_dist=load_dist, unaligned_ub_access=unaligned_ub_access, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class LocalMemBarOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.local_mem_bar"

  _ODS_REGIONS = (0, True)

  def __init__(self, barrier_kind, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["barrier_kind"] = (barrier_kind if (
    isinstance(barrier_kind, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64Attr')) else
      _ods_ir.AttrBuilder.get('I64Attr')(barrier_kind, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def barrier_kind(self):
    return self.operation.attributes["barrier_kind"]

  @barrier_kind.setter
  def barrier_kind(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["barrier_kind"] = value

def local_mem_bar(barrier_kind, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(LocalMemBarOp(barrier_kind=barrier_kind, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class LogOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.log"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, operand, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(operand))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def operand(self):
    return self.operation.operands[0]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 2 else self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def log(result, operand, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(LogOp(result=result, operand=operand, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeCoordOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_coord"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, dyn_elems, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(dyn_elems))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dyn_elems(self):
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def make_coord(result, dyn_elems, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeCoordOp(result=result, dyn_elems=dyn_elems, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeLayoutOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_layout"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, shape, stride, *, origin_shape=None, layoutTag=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(shape))
    operands.append(_get_op_result_or_value(stride))
    if origin_shape is not None: operands.append(_get_op_result_or_value(origin_shape))
    _ods_context = _ods_get_default_loc_context(loc)
    if layoutTag is not None: attributes["layoutTag"] = (layoutTag if (
        isinstance(layoutTag, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('StrAttr')) else
          _ods_ir.AttrBuilder.get('StrAttr')(layoutTag, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def shape(self):
    return self.operation.operands[0]

  @builtins.property
  def stride(self):
    return self.operation.operands[1]

  @builtins.property
  def origin_shape(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def layoutTag(self):
    if "layoutTag" not in self.operation.attributes:
      return None
    return self.operation.attributes["layoutTag"]

  @layoutTag.setter
  def layoutTag(self, value):
    if value is not None:
      self.operation.attributes["layoutTag"] = value
    elif "layoutTag" in self.operation.attributes:
      del self.operation.attributes["layoutTag"]

  @layoutTag.deleter
  def layoutTag(self):
    del self.operation.attributes["layoutTag"]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def make_layout(result, shape, stride, *, origin_shape=None, layout_tag=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeLayoutOp(result=result, shape=shape, stride=stride, origin_shape=origin_shape, layoutTag=layout_tag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeShapeOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_shape"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, dyn_elems, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(dyn_elems))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dyn_elems(self):
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def make_shape(result, dyn_elems, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeShapeOp(result=result, dyn_elems=dyn_elems, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeStrideOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_stride"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, dyn_elems, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(dyn_elems))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dyn_elems(self):
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def make_stride(result, dyn_elems, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeStrideOp(result=result, dyn_elems=dyn_elems, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeTensorLikeOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_tensor_like"

  _ODS_REGIONS = (0, True)

  def __init__(self, tile, ptr, like, layoutTag, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(ptr))
    operands.append(_get_op_result_or_value(like))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["layoutTag"] = (layoutTag if (
    isinstance(layoutTag, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(layoutTag, context=_ods_context))
    results.append(tile)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def ptr(self):
    return self.operation.operands[0]

  @builtins.property
  def like(self):
    return self.operation.operands[1]

  @builtins.property
  def layoutTag(self):
    return self.operation.attributes["layoutTag"]

  @layoutTag.setter
  def layoutTag(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["layoutTag"] = value

  @builtins.property
  def tile(self):
    return self.operation.results[0]

def make_tensor_like(tile, ptr, like, layout_tag, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeTensorLikeOp(tile=tile, ptr=ptr, like=like, layoutTag=layout_tag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeTensorOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_tensor"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, ptr, layout, coord, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(ptr))
    operands.append(_get_op_result_or_value(layout))
    operands.append(_get_op_result_or_value(coord))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def ptr(self):
    return self.operation.operands[0]

  @builtins.property
  def layout(self):
    return self.operation.operands[1]

  @builtins.property
  def coord(self):
    return self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def make_tensor(result, ptr, layout, coord, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeTensorOp(result=result, ptr=ptr, layout=layout, coord=coord, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MaxOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.max"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def max(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MaxOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MaxsOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.maxs"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def maxs(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MaxsOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MinOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.min"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def min(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MinOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MinsOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mins"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def mins(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MinsOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MmadOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mmad"

  _ODS_REGIONS = (0, True)

  def __init__(self, acc, lhs, rhs, init_c, unit_flag, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(acc))
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    operands.append(_get_op_result_or_value(init_c))
    operands.append(_get_op_result_or_value(unit_flag))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def acc(self):
    return self.operation.operands[0]

  @builtins.property
  def lhs(self):
    return self.operation.operands[1]

  @builtins.property
  def rhs(self):
    return self.operation.operands[2]

  @builtins.property
  def init_c(self):
    return self.operation.operands[3]

  @builtins.property
  def unit_flag(self):
    return self.operation.operands[4]

def mmad(acc, lhs, rhs, init_c, unit_flag, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(MmadOp(acc=acc, lhs=lhs, rhs=rhs, init_c=init_c, unit_flag=unit_flag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MulOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mul"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def mul(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MulOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MulsOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.muls"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def muls(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MulsOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MutexLockOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mutex_lock"

  _ODS_REGIONS = (0, True)

  def __init__(self, mutex, pipe, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(mutex))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["pipe"] = (pipe if (
    isinstance(pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(pipe, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def mutex(self):
    return self.operation.operands[0]

  @builtins.property
  def pipe(self):
    return self.operation.attributes["pipe"]

  @pipe.setter
  def pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["pipe"] = value

def mutex_lock(mutex, pipe, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(MutexLockOp(mutex=mutex, pipe=pipe, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MutexOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mutex"

  _ODS_REGIONS = (0, True)

  def __init__(self, mutex, resource, id, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["resource"] = (resource if (
    isinstance(resource, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(resource, context=_ods_context))
    attributes["id"] = (id if (
    isinstance(id, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64Attr')) else
      _ods_ir.AttrBuilder.get('I64Attr')(id, context=_ods_context))
    results.append(mutex)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def resource(self):
    return self.operation.attributes["resource"]

  @resource.setter
  def resource(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["resource"] = value

  @builtins.property
  def id(self):
    return self.operation.attributes["id"]

  @id.setter
  def id(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["id"] = value

  @builtins.property
  def mutex(self):
    return self.operation.results[0]

def mutex(mutex, resource, id, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MutexOp(mutex=mutex, resource=resource, id=id, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MutexUnlockOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mutex_unlock"

  _ODS_REGIONS = (0, True)

  def __init__(self, mutex, pipe, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(mutex))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["pipe"] = (pipe if (
    isinstance(pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(pipe, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def mutex(self):
    return self.operation.operands[0]

  @builtins.property
  def pipe(self):
    return self.operation.attributes["pipe"]

  @pipe.setter
  def pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["pipe"] = value

def mutex_unlock(mutex, pipe, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(MutexUnlockOp(mutex=mutex, pipe=pipe, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class NegOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.neg"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, operand, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(operand))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def operand(self):
    return self.operation.operands[0]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 2 else self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def neg(result, operand, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(NegOp(result=result, operand=operand, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class PipeBarrierOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.pipe_barrier"

  _ODS_REGIONS = (0, True)

  def __init__(self, pipe, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["pipe"] = (pipe if (
    isinstance(pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(pipe, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def pipe(self):
    return self.operation.attributes["pipe"]

  @pipe.setter
  def pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["pipe"] = value

def pipe_barrier(pipe, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(PipeBarrierOp(pipe=pipe, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class PtrAddOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.ptr_add"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, ptr, offset, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(ptr))
    operands.append(_get_op_result_or_value(offset))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def ptr(self):
    return self.operation.operands[0]

  @builtins.property
  def offset(self):
    return self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def ptr_add(result, ptr, offset, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(PtrAddOp(result=result, ptr=ptr, offset=offset, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class RecastPtrOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.recast_ptr"

  _ODS_REGIONS = (0, True)

  def __init__(self, ptr, src, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(src))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def src(self):
    return self.operation.operands[0]

  @builtins.property
  def ptr(self):
    return self.operation.results[0]

def recast_ptr(ptr, src, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(RecastPtrOp(ptr=ptr, src=src, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class ReduceOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.reduce"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, operand, kind, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(operand))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["kind"] = (kind if (
    isinstance(kind, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(kind, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def operand(self):
    return self.operation.operands[0]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 2 else self.operation.operands[1]

  @builtins.property
  def kind(self):
    return self.operation.attributes["kind"]

  @kind.setter
  def kind(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["kind"] = value

  @builtins.property
  def result(self):
    return self.operation.results[0]

def reduce(result, operand, kind, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(ReduceOp(result=result, operand=operand, kind=kind, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class ReturnOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.return"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

def return_(*, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(ReturnOp(loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class ScalarLoadOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.scalar_load"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, source, indices, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(source))
    operands.extend(_get_op_results_or_values(indices))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def source(self):
    return self.operation.operands[0]

  @builtins.property
  def indices(self):
    _ods_variadic_group_length = len(self.operation.operands) - 2 + 1
    return self.operation.operands[1:1 + _ods_variadic_group_length]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def scalar_load(result, source, indices, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(ScalarLoadOp(result=result, source=source, indices=indices, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class ScalarStoreOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.scalar_store"

  _ODS_REGIONS = (0, True)

  def __init__(self, dest, indices, value, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(dest))
    operands.extend(_get_op_results_or_values(indices))
    operands.append(_get_op_result_or_value(value))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dest(self):
    return self.operation.operands[0]

  @builtins.property
  def indices(self):
    _ods_variadic_group_length = len(self.operation.operands) - 3 + 1
    return self.operation.operands[1:1 + _ods_variadic_group_length]

  @builtins.property
  def value(self):
    _ods_variadic_group_length = len(self.operation.operands) - 3 + 1
    return self.operation.operands[2 + _ods_variadic_group_length - 1]

def scalar_store(dest, indices, value, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(ScalarStoreOp(dest=dest, indices=indices, value=value, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class SetFlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.set_flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(flag))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def flag(self):
    return self.operation.operands[0]

def set_flag(flag, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(SetFlagOp(flag=flag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class SqrtOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.sqrt"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, operand, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(operand))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def operand(self):
    return self.operation.operands[0]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 2 else self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def sqrt(result, operand, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(SqrtOp(result=result, operand=operand, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class SqueezeOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.squeeze"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, src, mask, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(src))
    operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def src(self):
    return self.operation.operands[0]

  @builtins.property
  def mask(self):
    return self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def squeeze(result, src, mask, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(SqueezeOp(result=result, src=src, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class StoreOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.store"

  _ODS_REGIONS = (0, True)

  def __init__(self, dest, source, *, mask=None, unaligned_ub_access=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(dest))
    operands.append(_get_op_result_or_value(source))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    if bool(unaligned_ub_access): attributes["unaligned_ub_access"] = _ods_ir.UnitAttr.get(
      _ods_get_default_loc_context(loc))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dest(self):
    return self.operation.operands[0]

  @builtins.property
  def source(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def unaligned_ub_access(self):
    return "unaligned_ub_access" in self.operation.attributes

  @unaligned_ub_access.setter
  def unaligned_ub_access(self, value):
    if bool(value):
      self.operation.attributes["unaligned_ub_access"] = _ods_ir.UnitAttr.get()
    elif "unaligned_ub_access" in self.operation.attributes:
      del self.operation.attributes["unaligned_ub_access"]

  @unaligned_ub_access.deleter
  def unaligned_ub_access(self):
    del self.operation.attributes["unaligned_ub_access"]

def store(dest, source, *, mask=None, unaligned_ub_access=None, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(StoreOp(dest=dest, source=source, mask=mask, unaligned_ub_access=unaligned_ub_access, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class SubBlockIdxOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.arch.sub_block_idx"

  _ODS_REGIONS = (0, True)

  def __init__(self, index, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(index)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def index(self):
    return self.operation.results[0]

def arch_sub_block_idx(index, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(SubBlockIdxOp(index=index, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class SubOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.sub"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def sub(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(SubOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class SubsOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.subs"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, mask=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    if mask is not None: operands.append(_get_op_result_or_value(mask))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def mask(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def subs(result, lhs, rhs, *, mask=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(SubsOp(result=result, lhs=lhs, rhs=rhs, mask=mask, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class TensorDescOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.tensor_desc"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, base, row_offset, col_offset, stride0, stride1, shape0, shape1, origin_shape0, origin_shape1, packed, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(base))
    operands.append(_get_op_result_or_value(row_offset))
    operands.append(_get_op_result_or_value(col_offset))
    operands.append(_get_op_result_or_value(stride0))
    operands.append(_get_op_result_or_value(stride1))
    operands.append(_get_op_result_or_value(shape0))
    operands.append(_get_op_result_or_value(shape1))
    operands.append(_get_op_result_or_value(origin_shape0))
    operands.append(_get_op_result_or_value(origin_shape1))
    operands.extend(_get_op_results_or_values(packed))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def base(self):
    return self.operation.operands[0]

  @builtins.property
  def row_offset(self):
    return self.operation.operands[1]

  @builtins.property
  def col_offset(self):
    return self.operation.operands[2]

  @builtins.property
  def stride0(self):
    return self.operation.operands[3]

  @builtins.property
  def stride1(self):
    return self.operation.operands[4]

  @builtins.property
  def shape0(self):
    return self.operation.operands[5]

  @builtins.property
  def shape1(self):
    return self.operation.operands[6]

  @builtins.property
  def origin_shape0(self):
    return self.operation.operands[7]

  @builtins.property
  def origin_shape1(self):
    return self.operation.operands[8]

  @builtins.property
  def packed(self):
    _ods_variadic_group_length = len(self.operation.operands) - 10 + 1
    return self.operation.operands[9:9 + _ods_variadic_group_length]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def tensor_desc(result, base, row_offset, col_offset, stride0, stride1, shape0, shape1, origin_shape0, origin_shape1, packed, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(TensorDescOp(result=result, base=base, row_offset=row_offset, col_offset=col_offset, stride0=stride0, stride1=stride1, shape0=shape0, shape1=shape1, origin_shape0=origin_shape0, origin_shape1=origin_shape1, packed=packed, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class TensorPtrOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.tensor_ptr"

  _ODS_REGIONS = (0, True)

  def __init__(self, ptr, src, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(src))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def src(self):
    return self.operation.operands[0]

  @builtins.property
  def ptr(self):
    return self.operation.results[0]

def tensor_ptr(ptr, src, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(TensorPtrOp(ptr=ptr, src=src, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class TileViewOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.tile_view"

  _ODS_REGIONS = (0, True)

  def __init__(self, view, source, shape, coord, *, layouttag=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(source))
    operands.append(_get_op_result_or_value(shape))
    operands.append(_get_op_result_or_value(coord))
    _ods_context = _ods_get_default_loc_context(loc)
    if layouttag is not None: attributes["layouttag"] = (layouttag if (
        isinstance(layouttag, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('StrAttr')) else
          _ods_ir.AttrBuilder.get('StrAttr')(layouttag, context=_ods_context))
    results.append(view)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def source(self):
    return self.operation.operands[0]

  @builtins.property
  def shape(self):
    return self.operation.operands[1]

  @builtins.property
  def coord(self):
    return self.operation.operands[2]

  @builtins.property
  def layouttag(self):
    if "layouttag" not in self.operation.attributes:
      return None
    return self.operation.attributes["layouttag"]

  @layouttag.setter
  def layouttag(self, value):
    if value is not None:
      self.operation.attributes["layouttag"] = value
    elif "layouttag" in self.operation.attributes:
      del self.operation.attributes["layouttag"]

  @layouttag.deleter
  def layouttag(self):
    del self.operation.attributes["layouttag"]

  @builtins.property
  def view(self):
    return self.operation.results[0]

def tile_view(view, source, shape, coord, *, layouttag=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(TileViewOp(view=view, source=source, shape=shape, coord=coord, layouttag=layouttag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class UpdateMaskOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.update_mask"

  _ODS_REGIONS = (0, True)

  def __init__(self, mask, new_true_shape, true_shape, dtype, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(true_shape))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["dtype"] = (dtype if (
    isinstance(dtype, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('TypeAttr')) else
      _ods_ir.AttrBuilder.get('TypeAttr')(dtype, context=_ods_context))
    results.append(mask)
    results.append(new_true_shape)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def true_shape(self):
    return self.operation.operands[0]

  @builtins.property
  def dtype(self):
    return self.operation.attributes["dtype"]

  @dtype.setter
  def dtype(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dtype"] = value

  @builtins.property
  def mask(self):
    return self.operation.results[0]

  @builtins.property
  def new_true_shape(self):
    return self.operation.results[1]

def update_mask(mask, new_true_shape, true_shape, dtype, *, loc=None, ip=None) -> _Sequence[_ods_ir.Value]:
  return _get_op_result_or_op_results(UpdateMaskOp(mask=mask, new_true_shape=new_true_shape, true_shape=true_shape, dtype=dtype, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class VecFuncOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.vec.func"

  _ODS_REGIONS = (1, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def body(self):
    return self.regions[0]

def vec_func(*, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(VecFuncOp(loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class VectorOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.vector"

  _ODS_REGIONS = (1, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def body(self):
    return self.regions[0]

def vector(*, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(VectorOp(loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class WaitFlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.wait_flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(flag))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def flag(self):
    return self.operation.operands[0]

def wait_flag(flag, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(WaitFlagOp(flag=flag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class WhereOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.where"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, mask, x, y, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(mask))
    operands.append(_get_op_result_or_value(x))
    operands.append(_get_op_result_or_value(y))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def mask(self):
    return self.operation.operands[0]

  @builtins.property
  def x(self):
    return self.operation.operands[1]

  @builtins.property
  def y(self):
    return self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def where(result, mask, x, y, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(WhereOp(result=result, mask=mask, x=x, y=y, loc=loc, ip=ip))
