
# Autogenerated by mlir-tblgen; don't manually edit.
from __future__ import annotations


from mlir.dialects._ods_common import _cext as _ods_cext
from mlir.dialects._ods_common import (
    equally_sized_accessor as _ods_equally_sized_accessor,
    get_default_loc_context as _ods_get_default_loc_context,
    get_op_result_or_op_results as _get_op_result_or_op_results,
    get_op_result_or_value as _get_op_result_or_value,
    get_op_results_or_values as _get_op_results_or_values,
    segmented_accessor as _ods_segmented_accessor,
)
_ods_ir = _ods_cext.ir

import builtins
from typing import Sequence as _Sequence, Union as _Union


@_ods_cext.register_dialect
class _Dialect(_ods_ir.Dialect):
  DIALECT_NAMESPACE = "tla"

@_ods_cext.register_operation(_Dialect)
class AddOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.add"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def add(result, lhs, rhs, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(AddOp(result=result, lhs=lhs, rhs=rhs, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class AllocPtrOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.alloc_ptr"

  _ODS_REGIONS = (0, True)

  def __init__(self, ptr, size_bytes, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["size_bytes"] = (size_bytes if (
    isinstance(size_bytes, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64Attr')) else
      _ods_ir.AttrBuilder.get('I64Attr')(size_bytes, context=_ods_context))
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def size_bytes(self):
    return self.operation.attributes["size_bytes"]

  @size_bytes.setter
  def size_bytes(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["size_bytes"] = value

  @builtins.property
  def ptr(self):
    return self.operation.results[0]

def alloc_ptr(ptr, size_bytes, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(AllocPtrOp(ptr=ptr, size_bytes=size_bytes, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class BlockDimOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.arch.block_dim"

  _ODS_REGIONS = (0, True)

  def __init__(self, dim, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(dim)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dim(self):
    return self.operation.results[0]

def arch_block_dim(dim, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(BlockDimOp(dim=dim, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class BlockIdxOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.arch.block_idx"

  _ODS_REGIONS = (0, True)

  def __init__(self, index, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(index)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def index(self):
    return self.operation.results[0]

def arch_block_idx(index, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(BlockIdxOp(index=index, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class BroadcastOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.broadcast"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, value, shape, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(value))
    operands.append(_get_op_result_or_value(shape))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def value(self):
    return self.operation.operands[0]

  @builtins.property
  def shape(self):
    return self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def broadcast(result, value, shape, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(BroadcastOp(result=result, value=value, shape=shape, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CopyL0C2DstParamsOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.CopyL0C2DstParams"

  _ODS_REGIONS = (0, True)

  def __init__(self, params, unit_flag, relu_enable, quant_mode, l0c2ub_mode, *, quant_scale_or_tensor=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    if quant_scale_or_tensor is not None: operands.append(_get_op_result_or_value(quant_scale_or_tensor))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["unit_flag"] = (unit_flag if (
    isinstance(unit_flag, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64Attr')) else
      _ods_ir.AttrBuilder.get('I64Attr')(unit_flag, context=_ods_context))
    attributes["relu_enable"] = (relu_enable if (
    isinstance(relu_enable, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('BoolAttr')) else
      _ods_ir.AttrBuilder.get('BoolAttr')(relu_enable, context=_ods_context))
    attributes["quant_mode"] = (quant_mode if (
    isinstance(quant_mode, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_QuantModeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_QuantModeAttr')(quant_mode, context=_ods_context))
    attributes["l0c2ub_mode"] = (l0c2ub_mode if (
    isinstance(l0c2ub_mode, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_L0C2UBModeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_L0C2UBModeAttr')(l0c2ub_mode, context=_ods_context))
    results.append(params)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def quant_scale_or_tensor(self):
    return None if len(self.operation.operands) < 1 else self.operation.operands[0]

  @builtins.property
  def unit_flag(self):
    return self.operation.attributes["unit_flag"]

  @unit_flag.setter
  def unit_flag(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["unit_flag"] = value

  @builtins.property
  def relu_enable(self):
    return self.operation.attributes["relu_enable"]

  @relu_enable.setter
  def relu_enable(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["relu_enable"] = value

  @builtins.property
  def quant_mode(self):
    return self.operation.attributes["quant_mode"]

  @quant_mode.setter
  def quant_mode(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["quant_mode"] = value

  @builtins.property
  def l0c2ub_mode(self):
    return self.operation.attributes["l0c2ub_mode"]

  @l0c2ub_mode.setter
  def l0c2ub_mode(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["l0c2ub_mode"] = value

  @builtins.property
  def params(self):
    return self.operation.results[0]

def CopyL0C2DstParams(params, unit_flag, relu_enable, quant_mode, l0c2ub_mode, *, quant_scale_or_tensor=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(CopyL0C2DstParamsOp(params=params, unit_flag=unit_flag, relu_enable=relu_enable, quant_mode=quant_mode, l0c2ub_mode=l0c2ub_mode, quant_scale_or_tensor=quant_scale_or_tensor, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CopyOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.copy"

  _ODS_REGIONS = (0, True)

  def __init__(self, dst, src, *, params=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(dst))
    operands.append(_get_op_result_or_value(src))
    if params is not None: operands.append(_get_op_result_or_value(params))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dst(self):
    return self.operation.operands[0]

  @builtins.property
  def src(self):
    return self.operation.operands[1]

  @builtins.property
  def params(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

def copy(dst, src, *, params=None, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(CopyOp(dst=dst, src=src, params=params, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CrossCoreSetFlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.cross_core_set_flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(flag))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def flag(self):
    return self.operation.operands[0]

def cross_core_set_flag(flag, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(CrossCoreSetFlagOp(flag=flag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CrossCoreWaitFlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.cross_core_wait_flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(flag))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def flag(self):
    return self.operation.operands[0]

def cross_core_wait_flag(flag, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(CrossCoreWaitFlagOp(flag=flag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CrossFlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.cross_flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, name, src_pipe, dst_pipe, *, mode=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["name"] = (name if (
    isinstance(name, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(name, context=_ods_context))
    attributes["src_pipe"] = (src_pipe if (
    isinstance(src_pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(src_pipe, context=_ods_context))
    attributes["dst_pipe"] = (dst_pipe if (
    isinstance(dst_pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(dst_pipe, context=_ods_context))
    if mode is not None: attributes["mode"] = (mode if (
        isinstance(mode, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('I64Attr')) else
          _ods_ir.AttrBuilder.get('I64Attr')(mode, context=_ods_context))
    results.append(flag)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def name(self):
    return self.operation.attributes["name"]

  @name.setter
  def name(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["name"] = value

  @builtins.property
  def src_pipe(self):
    return self.operation.attributes["src_pipe"]

  @src_pipe.setter
  def src_pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["src_pipe"] = value

  @builtins.property
  def dst_pipe(self):
    return self.operation.attributes["dst_pipe"]

  @dst_pipe.setter
  def dst_pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dst_pipe"] = value

  @builtins.property
  def mode(self):
    if "mode" not in self.operation.attributes:
      return None
    return self.operation.attributes["mode"]

  @mode.setter
  def mode(self, value):
    if value is not None:
      self.operation.attributes["mode"] = value
    elif "mode" in self.operation.attributes:
      del self.operation.attributes["mode"]

  @mode.deleter
  def mode(self):
    del self.operation.attributes["mode"]

  @builtins.property
  def flag(self):
    return self.operation.results[0]

def cross_flag(flag, name, src_pipe, dst_pipe, *, mode=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(CrossFlagOp(flag=flag, name=name, src_pipe=src_pipe, dst_pipe=dst_pipe, mode=mode, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class CubeOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.cube"

  _ODS_REGIONS = (1, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def body(self):
    return self.regions[0]

def cube(*, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(CubeOp(loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class DivOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.div"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def div(result, lhs, rhs, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(DivOp(result=result, lhs=lhs, rhs=rhs, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class FlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, name, src_pipe, dst_pipe, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["name"] = (name if (
    isinstance(name, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(name, context=_ods_context))
    attributes["src_pipe"] = (src_pipe if (
    isinstance(src_pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(src_pipe, context=_ods_context))
    attributes["dst_pipe"] = (dst_pipe if (
    isinstance(dst_pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(dst_pipe, context=_ods_context))
    results.append(flag)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def name(self):
    return self.operation.attributes["name"]

  @name.setter
  def name(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["name"] = value

  @builtins.property
  def src_pipe(self):
    return self.operation.attributes["src_pipe"]

  @src_pipe.setter
  def src_pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["src_pipe"] = value

  @builtins.property
  def dst_pipe(self):
    return self.operation.attributes["dst_pipe"]

  @dst_pipe.setter
  def dst_pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["dst_pipe"] = value

  @builtins.property
  def flag(self):
    return self.operation.results[0]

def flag(flag, name, src_pipe, dst_pipe, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(FlagOp(flag=flag, name=name, src_pipe=src_pipe, dst_pipe=dst_pipe, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class FmaOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.fma"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, acc, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    operands.append(_get_op_result_or_value(acc))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def acc(self):
    return self.operation.operands[2]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def fma(result, lhs, rhs, acc, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(FmaOp(result=result, lhs=lhs, rhs=rhs, acc=acc, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class FuncOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.func"

  _ODS_REGIONS = (1, True)

  def __init__(self, sym_name, function_type, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["sym_name"] = (sym_name if (
    isinstance(sym_name, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('SymbolNameAttr')) else
      _ods_ir.AttrBuilder.get('SymbolNameAttr')(sym_name, context=_ods_context))
    attributes["function_type"] = (function_type if (
    isinstance(function_type, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('TypeAttr')) else
      _ods_ir.AttrBuilder.get('TypeAttr')(function_type, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def sym_name(self):
    return self.operation.attributes["sym_name"]

  @sym_name.setter
  def sym_name(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["sym_name"] = value

  @builtins.property
  def function_type(self):
    return self.operation.attributes["function_type"]

  @function_type.setter
  def function_type(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["function_type"] = value

  @builtins.property
  def body(self):
    return self.regions[0]

def func(sym_name, function_type, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(FuncOp(sym_name=sym_name, function_type=function_type, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class GmAddOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.gm_add"

  _ODS_REGIONS = (0, True)

  def __init__(self, lhs, rhs, dst, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    operands.append(_get_op_result_or_value(dst))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def dst(self):
    return self.operation.operands[2]

def gm_add(lhs, rhs, dst, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(GmAddOp(lhs=lhs, rhs=rhs, dst=dst, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class HivmMemrefAsPtrOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.hivm_memref_as_ptr"

  _ODS_REGIONS = (0, True)

  def __init__(self, ptr, memref, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(memref))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def memref(self):
    return self.operation.operands[0]

  @builtins.property
  def ptr(self):
    return self.operation.results[0]

def hivm_memref_as_ptr(ptr, memref, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(HivmMemrefAsPtrOp(ptr=ptr, memref=memref, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class IntToPtrOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.inttoptr"

  _ODS_REGIONS = (0, True)

  def __init__(self, ptr, addr, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(addr))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def addr(self):
    return self.operation.operands[0]

  @builtins.property
  def ptr(self):
    return self.operation.results[0]

def inttoptr(ptr, addr, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(IntToPtrOp(ptr=ptr, addr=addr, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class LoadOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.load"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, source, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(source))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def source(self):
    return self.operation.operands[0]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def load(result, source, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(LoadOp(result=result, source=source, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeCoordOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_coord"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, dyn_elems, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(dyn_elems))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dyn_elems(self):
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def make_coord(result, dyn_elems, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeCoordOp(result=result, dyn_elems=dyn_elems, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeLayoutOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_layout"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, shape, stride, *, origin_shape=None, layoutTag=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(shape))
    operands.append(_get_op_result_or_value(stride))
    if origin_shape is not None: operands.append(_get_op_result_or_value(origin_shape))
    _ods_context = _ods_get_default_loc_context(loc)
    if layoutTag is not None: attributes["layoutTag"] = (layoutTag if (
        isinstance(layoutTag, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('StrAttr')) else
          _ods_ir.AttrBuilder.get('StrAttr')(layoutTag, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def shape(self):
    return self.operation.operands[0]

  @builtins.property
  def stride(self):
    return self.operation.operands[1]

  @builtins.property
  def origin_shape(self):
    return None if len(self.operation.operands) < 3 else self.operation.operands[2]

  @builtins.property
  def layoutTag(self):
    if "layoutTag" not in self.operation.attributes:
      return None
    return self.operation.attributes["layoutTag"]

  @layoutTag.setter
  def layoutTag(self, value):
    if value is not None:
      self.operation.attributes["layoutTag"] = value
    elif "layoutTag" in self.operation.attributes:
      del self.operation.attributes["layoutTag"]

  @layoutTag.deleter
  def layoutTag(self):
    del self.operation.attributes["layoutTag"]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def make_layout(result, shape, stride, *, origin_shape=None, layout_tag=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeLayoutOp(result=result, shape=shape, stride=stride, origin_shape=origin_shape, layoutTag=layout_tag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeShapeOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_shape"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, dyn_elems, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(dyn_elems))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dyn_elems(self):
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def make_shape(result, dyn_elems, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeShapeOp(result=result, dyn_elems=dyn_elems, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeStrideOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_stride"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, dyn_elems, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.extend(_get_op_results_or_values(dyn_elems))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dyn_elems(self):
    _ods_variadic_group_length = len(self.operation.operands) - 1 + 1
    return self.operation.operands[0:0 + _ods_variadic_group_length]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def make_stride(result, dyn_elems, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeStrideOp(result=result, dyn_elems=dyn_elems, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MakeTensorLikeOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.make_tensor_like"

  _ODS_REGIONS = (0, True)

  def __init__(self, tile, ptr, like, layoutTag, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(ptr))
    operands.append(_get_op_result_or_value(like))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["layoutTag"] = (layoutTag if (
    isinstance(layoutTag, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(layoutTag, context=_ods_context))
    results.append(tile)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def ptr(self):
    return self.operation.operands[0]

  @builtins.property
  def like(self):
    return self.operation.operands[1]

  @builtins.property
  def layoutTag(self):
    return self.operation.attributes["layoutTag"]

  @layoutTag.setter
  def layoutTag(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["layoutTag"] = value

  @builtins.property
  def tile(self):
    return self.operation.results[0]

def make_tensor_like(tile, ptr, like, layout_tag, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MakeTensorLikeOp(tile=tile, ptr=ptr, like=like, layoutTag=layout_tag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MmadOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mmad"

  _ODS_REGIONS = (0, True)

  def __init__(self, acc, lhs, rhs, init_c, unit_flag, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(acc))
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    operands.append(_get_op_result_or_value(init_c))
    operands.append(_get_op_result_or_value(unit_flag))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def acc(self):
    return self.operation.operands[0]

  @builtins.property
  def lhs(self):
    return self.operation.operands[1]

  @builtins.property
  def rhs(self):
    return self.operation.operands[2]

  @builtins.property
  def init_c(self):
    return self.operation.operands[3]

  @builtins.property
  def unit_flag(self):
    return self.operation.operands[4]

def mmad(acc, lhs, rhs, init_c, unit_flag, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(MmadOp(acc=acc, lhs=lhs, rhs=rhs, init_c=init_c, unit_flag=unit_flag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MulOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mul"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def mul(result, lhs, rhs, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MulOp(result=result, lhs=lhs, rhs=rhs, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MutexLockOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mutex_lock"

  _ODS_REGIONS = (0, True)

  def __init__(self, mutex, pipe, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(mutex))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["pipe"] = (pipe if (
    isinstance(pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(pipe, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def mutex(self):
    return self.operation.operands[0]

  @builtins.property
  def pipe(self):
    return self.operation.attributes["pipe"]

  @pipe.setter
  def pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["pipe"] = value

def mutex_lock(mutex, pipe, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(MutexLockOp(mutex=mutex, pipe=pipe, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MutexOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mutex"

  _ODS_REGIONS = (0, True)

  def __init__(self, mutex, resource, id, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["resource"] = (resource if (
    isinstance(resource, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('StrAttr')) else
      _ods_ir.AttrBuilder.get('StrAttr')(resource, context=_ods_context))
    attributes["id"] = (id if (
    isinstance(id, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('I64Attr')) else
      _ods_ir.AttrBuilder.get('I64Attr')(id, context=_ods_context))
    results.append(mutex)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def resource(self):
    return self.operation.attributes["resource"]

  @resource.setter
  def resource(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["resource"] = value

  @builtins.property
  def id(self):
    return self.operation.attributes["id"]

  @id.setter
  def id(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["id"] = value

  @builtins.property
  def mutex(self):
    return self.operation.results[0]

def mutex(mutex, resource, id, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(MutexOp(mutex=mutex, resource=resource, id=id, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class MutexUnlockOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.mutex_unlock"

  _ODS_REGIONS = (0, True)

  def __init__(self, mutex, pipe, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(mutex))
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["pipe"] = (pipe if (
    isinstance(pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(pipe, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def mutex(self):
    return self.operation.operands[0]

  @builtins.property
  def pipe(self):
    return self.operation.attributes["pipe"]

  @pipe.setter
  def pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["pipe"] = value

def mutex_unlock(mutex, pipe, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(MutexUnlockOp(mutex=mutex, pipe=pipe, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class PipeBarrierOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.pipe_barrier"

  _ODS_REGIONS = (0, True)

  def __init__(self, pipe, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["pipe"] = (pipe if (
    isinstance(pipe, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('Tla_PipeAttr')) else
      _ods_ir.AttrBuilder.get('Tla_PipeAttr')(pipe, context=_ods_context))
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def pipe(self):
    return self.operation.attributes["pipe"]

  @pipe.setter
  def pipe(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["pipe"] = value

def pipe_barrier(pipe, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(PipeBarrierOp(pipe=pipe, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class RecastPtrOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.recast_ptr"

  _ODS_REGIONS = (0, True)

  def __init__(self, ptr, src, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(src))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(ptr)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def src(self):
    return self.operation.operands[0]

  @builtins.property
  def ptr(self):
    return self.operation.results[0]

def recast_ptr(ptr, src, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(RecastPtrOp(ptr=ptr, src=src, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class ReturnOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.return"

  _ODS_REGIONS = (0, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

def return_(*, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(ReturnOp(loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class SetFlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.set_flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(flag))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def flag(self):
    return self.operation.operands[0]

def set_flag(flag, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(SetFlagOp(flag=flag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class SplatOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.splat"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, value, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    attributes["value"] = (value if (
    isinstance(value, _ods_ir.Attribute) or
    not _ods_ir.AttrBuilder.contains('AnyAttr')) else
      _ods_ir.AttrBuilder.get('AnyAttr')(value, context=_ods_context))
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def value(self):
    return self.operation.attributes["value"]

  @value.setter
  def value(self, value):
    if value is None:
      raise ValueError("'None' not allowed as value for mandatory attributes")
    self.operation.attributes["value"] = value

  @builtins.property
  def result(self):
    return self.operation.results[0]

def splat(result, value, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(SplatOp(result=result, value=value, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class StoreOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.store"

  _ODS_REGIONS = (0, True)

  def __init__(self, dest, source, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(dest))
    operands.append(_get_op_result_or_value(source))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def dest(self):
    return self.operation.operands[0]

  @builtins.property
  def source(self):
    return self.operation.operands[1]

def store(dest, source, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(StoreOp(dest=dest, source=source, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class SubBlockIdxOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.arch.sub_block_idx"

  _ODS_REGIONS = (0, True)

  def __init__(self, index, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(index)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def index(self):
    return self.operation.results[0]

def arch_sub_block_idx(index, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(SubBlockIdxOp(index=index, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class SubOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.sub"

  _ODS_REGIONS = (0, True)

  def __init__(self, result, lhs, rhs, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(lhs))
    operands.append(_get_op_result_or_value(rhs))
    _ods_context = _ods_get_default_loc_context(loc)
    results.append(result)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def lhs(self):
    return self.operation.operands[0]

  @builtins.property
  def rhs(self):
    return self.operation.operands[1]

  @builtins.property
  def result(self):
    return self.operation.results[0]

def sub(result, lhs, rhs, *, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(SubOp(result=result, lhs=lhs, rhs=rhs, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class TileViewOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.tile_view"

  _ODS_REGIONS = (0, True)

  def __init__(self, view, source, shape, coord, *, layouttag=None, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(source))
    operands.append(_get_op_result_or_value(shape))
    operands.append(_get_op_result_or_value(coord))
    _ods_context = _ods_get_default_loc_context(loc)
    if layouttag is not None: attributes["layouttag"] = (layouttag if (
        isinstance(layouttag, _ods_ir.Attribute) or
        not _ods_ir.AttrBuilder.contains('StrAttr')) else
          _ods_ir.AttrBuilder.get('StrAttr')(layouttag, context=_ods_context))
    results.append(view)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def source(self):
    return self.operation.operands[0]

  @builtins.property
  def shape(self):
    return self.operation.operands[1]

  @builtins.property
  def coord(self):
    return self.operation.operands[2]

  @builtins.property
  def layouttag(self):
    if "layouttag" not in self.operation.attributes:
      return None
    return self.operation.attributes["layouttag"]

  @layouttag.setter
  def layouttag(self, value):
    if value is not None:
      self.operation.attributes["layouttag"] = value
    elif "layouttag" in self.operation.attributes:
      del self.operation.attributes["layouttag"]

  @layouttag.deleter
  def layouttag(self):
    del self.operation.attributes["layouttag"]

  @builtins.property
  def view(self):
    return self.operation.results[0]

def tile_view(view, source, shape, coord, *, layouttag=None, loc=None, ip=None) -> _ods_ir.Value:
  return _get_op_result_or_op_results(TileViewOp(view=view, source=source, shape=shape, coord=coord, layouttag=layouttag, loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class VecFuncOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.vec.func"

  _ODS_REGIONS = (1, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def body(self):
    return self.regions[0]

def vec_func(*, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(VecFuncOp(loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class VectorOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.vector"

  _ODS_REGIONS = (1, True)

  def __init__(self, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def body(self):
    return self.regions[0]

def vector(*, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(VectorOp(loc=loc, ip=ip))

@_ods_cext.register_operation(_Dialect)
class WaitFlagOp(_ods_ir.OpView):
  OPERATION_NAME = "tla.wait_flag"

  _ODS_REGIONS = (0, True)

  def __init__(self, flag, *, loc=None, ip=None):
    operands = []
    results = []
    attributes = {}
    regions = None
    operands.append(_get_op_result_or_value(flag))
    _ods_context = _ods_get_default_loc_context(loc)
    _ods_successors = None
    super().__init__(self.build_generic(attributes=attributes, results=results, operands=operands, successors=_ods_successors, regions=regions, loc=loc, ip=ip))

  @builtins.property
  def flag(self):
    return self.operation.operands[0]

def wait_flag(flag, *, loc=None, ip=None) -> _ods_ir.Operation:
  return _get_op_result_or_op_results(WaitFlagOp(flag=flag, loc=loc, ip=ip))
