[network.stream2.task0.subtask0.thread0]
	stream_id = 2
	task_id = 0
	subtask_id = 0
	thread_id = 0
	thread_dim = 1
    type = "MIXAIC"
    block_dim = 20
    core_list = [0, 3, 6, 13, 9, 7, 8, 5, 1, 2, 4, 10, 17, 18, 16, 14, 11, 12, 19, 15]
	start_cycle = 11667
	end_cycle = 85210
	duration = 73543
	first_blk_start_cycle = 11675
