from __future__ import annotations

import argparse
import difflib
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TLA_TD = (
    REPO_ROOT
    / "csrc"
    / "mlir"
    / "include"
    / "Dialect"
    / "Tla"
    / "IR"
    / "Tla.td"
)
OUT = REPO_ROOT / "catlass" / "_mlir_bindings" / "tla_ops_gen.py"


def _resolve_tblgen(explicit: str | None = None) -> str:
    if explicit:
        p = Path(explicit)
        if p.is_file():
            return str(p)
        raise SystemExit(f"mlir-tblgen not found: {p}")
    prebuilt = os.environ.get("TLA_DSL_PREBUILT_ASCENDNPU_IR")
    if prebuilt:
        p = Path(prebuilt) / "build" / "bin" / "mlir-tblgen"
        if p.is_file():
            return str(p)
    tblgen = shutil.which("mlir-tblgen")
    if tblgen:
        return tblgen
    raise SystemExit("mlir-tblgen not found in PATH")


def _resolve_include(explicit: str | None = None) -> Path:
    if explicit:
        p = Path(explicit)
        if (p / "mlir" / "IR" / "OpBase.td").is_file():
            return p
        raise SystemExit(f"include dir does not contain mlir/IR/OpBase.td: {p}")
    env = os.environ.get("MLIR_TBLGEN_INCLUDE_DIR")
    if env:
        p = Path(env)
        if (p / "mlir" / "IR" / "OpBase.td").is_file():
            return p
        raise SystemExit(
            f"MLIR_TBLGEN_INCLUDE_DIR does not contain mlir/IR/OpBase.td: {p}"
        )
    conda_prefix = os.environ.get("CONDA_PREFIX")
    if conda_prefix:
        p = Path(conda_prefix) / "include"
        if (p / "mlir" / "IR" / "OpBase.td").is_file():
            return p
    try:
        proc = subprocess.run(
            ["llvm-config", "--includedir"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        proc = None
    if proc is not None and proc.returncode == 0:
        p = Path(proc.stdout.strip())
        if (p / "mlir" / "IR" / "OpBase.td").is_file():
            return p
    raise SystemExit(
        "Unable to resolve MLIR include dir. Set MLIR_TBLGEN_INCLUDE_DIR or CONDA_PREFIX."
    )


def _rewrite_imports(text: str) -> str:
    text = text.replace(
        "# Autogenerated by mlir-tblgen; don't manually edit.\n",
        "# Autogenerated by mlir-tblgen; don't manually edit.\n"
        "from __future__ import annotations\n\n",
        1,
    )
    text = text.replace(
        "from ._ods_common import _cext as _ods_cext",
        "from mlir.dialects._ods_common import _cext as _ods_cext",
    )
    text = text.replace(
        "from ._ods_common import (",
        "from mlir.dialects._ods_common import (",
    )
    text = text.replace(
        "_ods_cext.globals.register_traceback_file_exclusion(__file__)",
        'if hasattr(_ods_cext.globals, "register_traceback_file_exclusion"):\n'
        "  _ods_cext.globals.register_traceback_file_exclusion(__file__)",
    )
    text = re.sub(r"_ods_ir\.OpResult\[[^\]]+\]", "_ods_ir.OpResult", text)
    text = re.sub(r"_ods_ir\.Value\[[^\]]+\]", "_ods_ir.Value", text)
    return text


def _generate(tblgen_arg: str | None = None, include_arg: str | None = None) -> str:
    tblgen = _resolve_tblgen(tblgen_arg)
    include = _resolve_include(include_arg)
    with tempfile.TemporaryDirectory() as tmp:
        tmp_out = Path(tmp) / "tla_ops_gen.py"
        cmd = [
            tblgen,
            "-gen-python-op-bindings",
            "-bind-dialect=tla",
            "-I",
            str(include),
            str(TLA_TD),
            "-o",
            str(tmp_out),
        ]
        proc = subprocess.run(cmd, check=False, capture_output=True, text=True)
        if proc.returncode != 0:
            raise SystemExit(
                "Failed to generate Tla Python op bindings.\n"
                f"Command: {' '.join(cmd)}\n"
                f"stdout:\n{proc.stdout}\n"
                f"stderr:\n{proc.stderr}"
            )
        text = tmp_out.read_text()
    return _rewrite_imports(text)


def _check(expected: str) -> int:
    if not OUT.exists():
        print(f"missing generated file: {OUT}")
        return 1
    current = OUT.read_text()
    if current == expected:
        print("tla_ops_gen.py is up to date")
        return 0
    diff = difflib.unified_diff(
        current.splitlines(),
        expected.splitlines(),
        fromfile=str(OUT),
        tofile="generated",
        lineterm="",
    )
    print("\n".join(diff))
    return 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--tblgen", help="Path to mlir-tblgen.")
    parser.add_argument(
        "--include-dir",
        help="MLIR TableGen include dir containing mlir/IR/OpBase.td.",
    )
    args = parser.parse_args()

    generated = _generate(args.tblgen, args.include_dir)
    if args.check:
        return _check(generated)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(generated)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
