from __future__ import annotations

import argparse
import difflib
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TLA_TD = (
    REPO_ROOT
    / "csrc"
    / "mlir"
    / "include"
    / "Dialect"
    / "Tla"
    / "IR"
    / "Tla.td"
)
OUT = REPO_ROOT / "catlass" / "_mlir_bindings" / "tla_ops_gen.py"


def _resolve_tblgen() -> str:
    tblgen = shutil.which("mlir-tblgen")
    if tblgen:
        return tblgen
    raise SystemExit("mlir-tblgen not found in PATH")


def _resolve_include() -> Path:
    env = os.environ.get("MLIR_TBLGEN_INCLUDE_DIR")
    if env:
        p = Path(env)
        if (p / "mlir" / "IR" / "OpBase.td").is_file():
            return p
        raise SystemExit(
            f"MLIR_TBLGEN_INCLUDE_DIR does not contain mlir/IR/OpBase.td: {p}"
        )
    conda_prefix = os.environ.get("CONDA_PREFIX")
    if conda_prefix:
        p = Path(conda_prefix) / "include"
        if (p / "mlir" / "IR" / "OpBase.td").is_file():
            return p
    try:
        proc = subprocess.run(
            ["llvm-config", "--includedir"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        proc = None
    if proc is not None and proc.returncode == 0:
        p = Path(proc.stdout.strip())
        if (p / "mlir" / "IR" / "OpBase.td").is_file():
            return p
    raise SystemExit(
        "Unable to resolve MLIR include dir. Set MLIR_TBLGEN_INCLUDE_DIR or CONDA_PREFIX."
    )


def _rewrite_imports(text: str) -> str:
    text = text.replace(
        "# Autogenerated by mlir-tblgen; don't manually edit.\n",
        "# Autogenerated by mlir-tblgen; don't manually edit.\n"
        "from __future__ import annotations\n\n",
        1,
    )
    text = text.replace(
        "from ._ods_common import _cext as _ods_cext",
        "from mlir.dialects._ods_common import _cext as _ods_cext",
    )
    text = text.replace(
        "from ._ods_common import (",
        "from mlir.dialects._ods_common import (",
    )
    text = text.replace(
        "_ods_cext.globals.register_traceback_file_exclusion(__file__)",
        'if hasattr(_ods_cext.globals, "register_traceback_file_exclusion"):\n'
        "  _ods_cext.globals.register_traceback_file_exclusion(__file__)",
    )
    text = re.sub(r"_ods_ir\.OpResult\[[^\]]+\]", "_ods_ir.OpResult", text)
    text = re.sub(r"_ods_ir\.Value\[[^\]]+\]", "_ods_ir.Value", text)
    text = text.replace(
        "def __init__(self, flag, *, loc=None, ip=None):\n"
        "    operands = []\n"
        "    results = []\n"
        "    attributes = {}\n"
        "    regions = None\n"
        "    operands.append(_get_op_result_or_value(flag))",
        "def __init__(self, cross_flag_value, *, loc=None, ip=None):\n"
        "    operands = []\n"
        "    results = []\n"
        "    attributes = {}\n"
        "    regions = None\n"
        "    operands.append(_get_op_result_or_value(cross_flag_value))",
        2,
    )
    text = text.replace(
        "def cross_core_set_flag(flag, *, loc=None, ip=None) -> _ods_ir.Operation:\n"
        "  return _get_op_result_or_op_results(CrossCoreSetFlagOp(flag=flag, loc=loc, ip=ip))",
        "def cross_core_set_flag(cross_flag_value, *, loc=None, ip=None) -> _ods_ir.Operation:\n"
        "  return _get_op_result_or_op_results(CrossCoreSetFlagOp(cross_flag_value=cross_flag_value, loc=loc, ip=ip))",
    )
    text = text.replace(
        "def cross_core_wait_flag(flag, *, loc=None, ip=None) -> _ods_ir.Operation:\n"
        "  return _get_op_result_or_op_results(CrossCoreWaitFlagOp(flag=flag, loc=loc, ip=ip))",
        "def cross_core_wait_flag(cross_flag_value, *, loc=None, ip=None) -> _ods_ir.Operation:\n"
        "  return _get_op_result_or_op_results(CrossCoreWaitFlagOp(cross_flag_value=cross_flag_value, loc=loc, ip=ip))",
    )
    text = text.replace(
        "def __init__(self, flag, name, src_pipe, dst_pipe, mode=None, *, loc=None, ip=None):",
        "def __init__(self, cross_flag_value, name, src_pipe, dst_pipe, mode=None, *, loc=None, ip=None):",
        1,
    )
    text = text.replace("    results.append(flag)", "    results.append(cross_flag_value)", 1)
    text = text.replace(
        "def cross_flag(flag, name, src_pipe, dst_pipe, mode=None, *, loc=None, ip=None) -> _ods_ir.Value:\n"
        "  return _get_op_result_or_op_results(CrossFlagOp(flag=flag, name=name, src_pipe=src_pipe, dst_pipe=dst_pipe, mode=mode, loc=loc, ip=ip))",
        "def cross_flag(cross_flag_value, name, src_pipe, dst_pipe, mode=None, *, loc=None, ip=None) -> _ods_ir.Value:\n"
        "  return _get_op_result_or_op_results(CrossFlagOp(cross_flag_value=cross_flag_value, name=name, src_pipe=src_pipe, dst_pipe=dst_pipe, mode=mode, loc=loc, ip=ip))",
    )
    return text


def _generate() -> str:
    tblgen = _resolve_tblgen()
    include = _resolve_include()
    with tempfile.TemporaryDirectory() as tmp:
        tmp_out = Path(tmp) / "tla_ops_gen.py"
        cmd = [
            tblgen,
            "-gen-python-op-bindings",
            "-bind-dialect=tla",
            "-I",
            str(include),
            str(TLA_TD),
            "-o",
            str(tmp_out),
        ]
        proc = subprocess.run(cmd, check=False, capture_output=True, text=True)
        if proc.returncode != 0:
            raise SystemExit(
                "Failed to generate Tla Python op bindings.\n"
                f"Command: {' '.join(cmd)}\n"
                f"stdout:\n{proc.stdout}\n"
                f"stderr:\n{proc.stderr}"
            )
        text = tmp_out.read_text()
    return _rewrite_imports(text)


def _check(expected: str) -> int:
    if not OUT.exists():
        print(f"missing generated file: {OUT}")
        return 1
    current = OUT.read_text()
    if current == expected:
        print("tla_ops_gen.py is up to date")
        return 0
    diff = difflib.unified_diff(
        current.splitlines(),
        expected.splitlines(),
        fromfile=str(OUT),
        tofile="generated",
        lineterm="",
    )
    print("\n".join(diff))
    return 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = _generate()
    if args.check:
        return _check(generated)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(generated)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
