name: arm_pre_smoke

on:
  workflow_call:
    inputs:
      task_name:
        required: true
        type: string
      image_version:
        required: true
        type: string

jobs:
  JOB_pre_smoke:
    name: pre_smoke_catlass
    steps:
      -
        name: Checkout
        identifier: process_checkout
        uses: checkout
        with:
          ref: ${{ atomgit.event.pull_request.merge_commit_sha || atomgit.sha }}
          allow-unsafe-pr-checkout: true

      -
        name: download
        uses: obs-download
        with:
          endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
          bucket: "ascend-ci"
          access-key: ${{ secrets.AK }}
          secret-key: ${{ secrets.SK }}
          key: |
            ${{ env.obs_path }}/pr_filelist.txt
            ${{ env.obs_path }}/pr_filelist_mod.txt
            ${{ env.obs_path }}/pre_smoke.sh
          path: ${{ steps.process_checkout.outputs.path }}

      -
        name: pre_smoke_catlass
        timeout-minutes: 300
        run: |
          set -e
          # set env
          export repo_name=${{env.repo_name}}
          export pr_id=${{ env.MERGE_ID }}
          export AK=${{secrets.AK}}
          export SK=${{secrets.SK}}
          export obs_smoke_path=${{ env.obs_smoke_path_A2 }}
          export obs_path=${{ env.obs_path }}
          export WORKSPACE=${{ steps.process_checkout.outputs.path }}
          whoami
          pwd
          sudo bash ${{ steps.process_checkout.outputs.path }}/pre_smoke.sh

    if: "${{ default() }}"
    runs-on: ['self-hosted','npu=2','smoke=204']
    container:
          image: swr.cn-north-4.myhuaweicloud.com/hw-ascend/${{ inputs.image_version }}

